module.exports = {
  Bagalkot: 'ABG',
  Ambala: 'ABM',
  Bathinda: 'ABT',
  Agra: 'AGR',
  Ahmedabad: 'AMD',
  Amritsar: 'ATQ',
  Alwar: 'AWR',
  Kozhikode: 'AZH',
  Munnar: 'AZQ',
  'Mount Abu': 'AZU',
  'Sasan Gir': 'AZX',
  Mararikulam: 'AZY',
  Bhubhaneshwar: 'BBI',
  Baddi: 'BD1',
  Vadodara: 'BDQ',
  Bellary: 'BEX',
  'Bharuch area': 'BHC',
  Bhopal: 'BHO',
  Bikaner: 'BKB',
  Bangalore: 'BLR',
  Mumbai: 'BOM',
  'Bhandavgarh National Park': 'BP1',
  'Kolkata-Calcutta': 'CCU',
  Poovar: 'CD1',
  Hassan: 'CD2',
  Kanyakumari: 'CDM',
  'Chennai (Madras)': 'CNN',
  'Kochi-Cochin': 'COK',
  Darjeeling: 'DAI',
  Dehradun: 'DED',
  'Delhi and NCR': 'DEL',
  Dharamshala: 'DHM',
  Barmer: 'EBM',
  Gangtok: 'GAG',
  Guwahati: 'GAU',
  Goa: 'GOO',
  Gwalior: 'GWL',
  Khajuraho: 'HJR',
  Hospet: 'HP1',
  Chittorgarh: 'HTC',
  Hyderabad: 'HYD',
  Bilaspur: 'IAB',
  Indore: 'IDR',
  Ranthambhore: 'IN0',
  Haridwar: 'IN1',
  Rishikesh: 'IN2',
  'Corbett National Park': 'IN3',
  Manali: 'IN6',
  Bharatpur: 'IN7',
  Mandawa: 'IN8',
  'Ajmer-Pushkar': 'IN9',
  Gandhinagar: 'ISK',
  Agartala: 'IXA',
  Chandigarh: 'IXC',
  Mangalore: 'IXE',
  Madurai: 'IXM',
  Aurangabad: 'IXU',
  Jamshedpur: 'IXW',
  'Andaman & Nicobar Island': 'IXZ',
  Jaipur: 'JAI',
  Jalandhar: 'JAL',
  Jamnagar: 'JAM',
  Jodhpur: 'JDH',
  Joshimath: 'JOS',
  Jaisalmer: 'JSA',
  Kachchh: 'KAC',
  Kodaikanal: 'KDO',
  Kumarakom: 'KK1',
  Kanpur: 'KNU',
  'Kanha National Park': 'KT1',
  Lucknow: 'LKO',
  'Mamallapuram-Mahabalipuram': 'LM1',
  Ludhiana: 'LUH',
  Mysore: 'MYQ',
  Nagpur: 'NAG',
  Nasik: 'NAS',
  Roorkee: 'NN2',
  Durgapur: 'NN3',
  Siliguri: 'NN4',
  Kakinada: 'OO1',
  Vapi: 'OO2',
  Manipal: 'OO3',
  Lonavala: 'OO5',
  Mahabaleshwar: 'OO6',
  Hosur: 'OO7',
  Tirupur: 'OO8',
  Mussoorie: 'OO9',
  Ooty: 'OOT',
  Pantnagar: 'PGH',
  Pune: 'PNQ',
  Pondicherry: 'PNY',
  Panipat: 'PPA',
  Kovalam: 'PQP',
  Puri: 'PU1',
  Puttaparthi: 'PUT',
  Alleppey: 'PYP',
  'Periyar-Thekkadi': 'PZP',
  Rajkot: 'RAJ',
  Raipur: 'RUR',
  Shimla: 'SLV',
  Surat: 'STV',
  Srinagar: 'SXR',
  Tirupati: 'TIR',
  Trivandrum: 'TV1',
  Udaipur: 'UDA',
  Udupi: 'UDP',
  Vijayawada: 'VGA',
  Varanasi: 'VNS',
  Visakhapatnam: 'VTZ',
  Vyttiri: 'VYT',
  Zirakpur: 'ZI1',
};

